// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyC5-NctncFG80jkOfChQqc2tHtpremoV-A',
  appId: '1:183467337649:web:0153252cae30eba109bf90',
  messagingSenderId: '183467337649',
  projectId: 'doanmobi-eafbe',
  authDomain: 'doanmobi-eafbe.firebaseapp.com',
  storageBucket: 'doanmobi-eafbe.appspot.com',
  measurementId: 'G-70Q7NNTPQR',
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WyYyHxWuhEZJLYzcLeNKab6h3V5eWiM',
    appId: '1:183467337649:android:4a6703afc0ec863609bf90',
    messagingSenderId: '183467337649',
    projectId: 'doanmobi-eafbe',
    storageBucket: 'doanmobi-eafbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnD72MoknaHt4jT8MHZBMh_XXU8Pl6nPM',
    appId: '1:183467337649:ios:3aeccbf7dda2b0f509bf90',
    messagingSenderId: '183467337649',
    projectId: 'doanmobi-eafbe',
    storageBucket: 'doanmobi-eafbe.firebasestorage.app',
    iosBundleId: 'com.example.doanMobi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnD72MoknaHt4jT8MHZBMh_XXU8Pl6nPM',
    appId: '1:183467337649:ios:3aeccbf7dda2b0f509bf90',
    messagingSenderId: '183467337649',
    projectId: 'doanmobi-eafbe',
    storageBucket: 'doanmobi-eafbe.firebasestorage.app',
    iosBundleId: 'com.example.doanMobi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-NctncFG80jkOfChQqc2tHtpremoV-A',
    appId: '1:183467337649:web:0153252cae30eba109bf90',
    messagingSenderId: '183467337649',
    projectId: 'doanmobi-eafbe',
    authDomain: 'doanmobi-eafbe.firebaseapp.com',
    storageBucket: 'doanmobi-eafbe.firebasestorage.app',
    measurementId: 'G-70Q7NNTPQR',
  );
}
